variables:
  TF_CLI_ARGS_init: "-lockfile=readonly"
  TF_VAR_pve_api_url: ${PVE_API_URL}
  TF_VAR_pve_user: ${PVE_USER}
  TF_VAR_pve_password: ${PVE_PASSWORD}
  TSFILE: "tailscale_1.28.0_amd64.tgz"

include:
  - component: $CI_SERVER_FQDN/components/opentofu/validate-plan-apply@0.21.0
    inputs:
      version: 0.21.0
      opentofu_version: 1.7.1
      root_dir: homelab/opentofu/proxmoxve/trinity-helios
      state_name: latest_trinity_helios_pve
      auto_apply: true

tailscale_setup:
  stage: setup
  image: debian:bullseye-slim
  before_script:
    - apt-get update -qq && apt-get install -y iptables wget
  script:
    - cd /usr/local/bin
    - wget https://pkgs.tailscale.com/stable/${TSFILE} -P /tmp
    - tar xzf /tmp/${TSFILE} --strip-components=1
    - rm /tmp/${TSFILE}
    - mkdir /var/run/tailscale
    - update-alternatives --set iptables /usr/sbin/iptables-legacy
    - tailscaled --state="mem:" &
    - tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname="gitlab-$(cat /etc/hostname)" --accept-routes
    - tailscale status

stages: [setup, validate, test, build, deploy]

plan:
  needs:
    - tailscale_setup
  before_script:
    - apk add jq
    - cat /etc/resolv.conf
