---
- name: Correct apt sources
  ansible.builtin.copy:
    content: |
      deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib
      deb http://deb.debian.org/debian {{ ansible_distribution_release }}-updates main contrib
      deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
