---
- name: Remove pve-enterprise repo
  ansible.builtin.copy:
    content: |
      # deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    owner: root
    group: root
    mode: '0644'

- name: Remove ceph enterprise repo
  ansible.builtin.copy:
    content: |
      # deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise
    dest: /etc/apt/sources.list.d/ceph.list
    owner: root
    group: root
    mode: '0644'
