---
- name: Remove ProxmoxVE subscription popup nag
  ansible.builtin.shell: |
    sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
  changed_when: false

- name: Reinstall proxmox-widget-toolkit
  ansible.builtin.apt:
    name: proxmox-widget-toolkit
    state: present
    force: yes
    update_cache: yes

- name: Subscription nag disabled message
  ansible.builtin.debug:
    msg: "Subscription nag is disabled (Remember to delete browser cache, if you are still getting it)"
