- hosts: "localhost"

  tasks:
    #PVE configs
    #apt update
    # deploy deb ci vm tmpl
    # tailscale (sops)
    #- name: Updating apt packages list and dist-upgrading
    #  ansible.builtin.apt:
    #    upgrade: dist
    #    update_cache: yes

    - name: Add Tailscale's package signing key and repository
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
        | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
        && curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list
        | tee /etc/apt/sources.list.d/tailscale.list

    - name: Install tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: yes

    #- name: Connecting to tailscale network
    #  ansible.builtin.include_role:
    #  name: artis3n.tailscale
