- hosts: "localhost"

  tasks:
    #PVE configs
    #apt update
    # deploy deb ci vm tmpl
    # tailscale (sops)
    #- name: Updating apt packages list and dist-upgrading
    #  ansible.builtin.apt:
    #    upgrade: dist
    #    update_cache: yes

    - name: Installing tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: yes

    #- name: Connecting to tailscale network
    #  ansible.builtin.include_role:
    #  name: artis3n.tailscale
