---
- name: Add IP forwarding configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "net.ipv4.ip_forward = 1"
    - "net.ipv6.conf.all.forwarding = 1"

- name: Apply sysctl changes
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
  changed_when: false
