---
- name: Connect to Tailnet
  ansible.builtin.include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ tailscale_authkey_var }}"
    tailscale_tags: "{{ tailscale_tags_var }}"
    tailscale_args: "{{ tailscale_args_var }}"
