---
- name: Correct Proxmox VE Sources
  ansible.builtin.copy:
    content: |
      deb http://deb.debian.org/debian bookworm main contrib
      deb http://deb.debian.org/debian bookworm-updates main contrib
      deb http://security.debian.org/debian-security bookworm-security main contrib
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Remove pve-enterprise repo
  ansible.builtin.copy:
    content: |
      # deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    owner: root
    group: root
    mode: '0644'

- name: Remove ceph enterprise repo
  ansible.builtin.copy:
    content: |
      # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    dest: /etc/apt/sources.list.d/ceph.list
    owner: root
    group: root
    mode: '0644'

- name: Add pve-no-subscription repo
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    state: present

- name: Remove Proxmox subscription popup nag
  ansible.builtin.shell: |
    sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
  changed_when: false

- name: Reinstall proxmox-widget-toolkit
  ansible.builtin.apt:
    name: proxmox-widget-toolkit
    state: present
    force: yes
    update_cache: yes

- name: Subscription nag disabled message
  ansible.builtin.debug:
    msg: "Subscription nag is disabled (Remember to delete browser cache, if you are still getting it)"

- name: Check if pve-ha-lrm is active
  ansible.builtin.command: systemctl is-active pve-ha-lrm
  register: ha_status
  changed_when: false
  failed_when: false

- name: Disable and stop HA services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - pve-ha-lrm
    - pve-ha-crm
    - corosync
  when: ha_status.rc == 0
