---
- name: Add Tailscale's package signing key and repository
  ansible.builtin.shell: >
    curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    && curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list
    | tee /etc/apt/sources.list.d/tailscale.list
  changed_when: false

- name: Install tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: yes

- name: Add IP forwarding configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "net.ipv4.ip_forward = 1"
    - "net.ipv6.conf.all.forwarding = 1"

- name: Apply sysctl changes
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
  changed_when: false

- name: Connect to Tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ tailscale_authkey_var }}"
    tailscale_tags: ['deviceofspace']
    tailscale_args: "--advertise-routes=10.27.9.0/24 --accept-routes --ssh"
