- hosts: "{{ desired_hosts }}"

  roles:
    - role: "proxmoxve_common"

    - role: "correct_package_manager_sources"

    - role: "update_packages"
      vars:
        apt_upgrade_type: "{{ desired_apt_upgrade_type }}"

    - role: "connect_tailscale"
      vars:
        tailscale_tags_var: "{{ desired_tailscale_tags }}"
        tailscale_args_var: "{{ desired_tailscale_args }}"
        tailscale_authkey_var: "{{ desired_tailscale_authkey }}"

    - role: "proxmoxve_vm_templates"
      vars:
        vm_id: "{{ desired_vm_id }}"
        vm_name: "{{ desired_vm_name }}"
        image_url: "{{ desired_image_url }}"
        image_name: "{{ desired_image_name }}"
        storage: "{{ desired_storage }}"
